# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_key', models.CharField(max_length=200)),
                ('scoreboard', django.contrib.postgres.fields.jsonb.JSONField()),
                ('luck', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
