# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='modified',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
