# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_graphs', '0002_auto_20171126_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_key', models.CharField(max_length=200)),
                ('scoreboard', django.contrib.postgres.fields.jsonb.JSONField()),
                ('luck', models.DecimalField(decimal_places=5, max_digits=5)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
