# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_graphs', '0003_auto_20171202_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='luck',
            field=models.IntegerField(),
        ),
    ]
